const IMAGE_FILES: Record<string, string> = {
  american_double: "american_double.png",
  american_single: "american_single.png",
  atomic_double: "atomic_double.png",
  atomic_sauce: "atomic_sauce.png",
  atomic_single: "atomic_single.png",
  berry_redbull_mojito: "berry_redbull_mojito.png",
  blended_double_matcha_latte: "blended_double_matcha_latte.png",
  blended_latte: "blended_latte.png",
  blended_matcha_latte: "blended_matcha_latte.png",
  blended_pistachio_latte: "blended_pistachio_latte.png",
  blended_pistachio_matcha: "blended_pistachio_matcha.png",
  blended_salted_caramel_latte: "blended_salted_caramel_latte.png",
  blended_salted_hazelnut_latte: "blended_salted_hazelnut_latte.png",
  blended_salted_vanilla_bean_latte: "blended_salted_vanilla_bean_latte.png",
  blended_salted_vanilla_bean_matcha: "blended_salted_vanilla_bean_matcha.png",
  blended_spanish_latte: "blended_spanish_latte.png",
  blended_spanish_matcha: "blended_spanish_matcha.png",
  blended_strawberry_matcha: "blended_strawberry_matcha.png",
  blended_white_matcha: "blended_white_matcha.png",
  blended_white_mocha_latte: "blended_white_mocha_latte.png",
  blueberry: "blueberry.png",
  blueberry_lemonade_shaker: "blueberry_lemonade_shaker.png",
  blueberry_mojito: "blueberry_mojito.png",
  blue_cheese: "blue_cheese.PNG",
  brgr_fries: "brgr_fries.png",
  brgr_sauce: "brgr_sauce.png",
  buffalo_bites: "buffalo_bites.png",
  buffalo_chkn: "buffalo_chkn.png",
  buffalo_sauce: "buffalo_sauce.png",
  buttermilk_herb_mayo: "buttermilk_herb_mayo.png",
  cali_sauce: "cali_sauce.png",
  cappuccino_l: "cappuccino_l.png",
  cappuccino_m: "cappuccino_m.png",
  cheese_fries: "cheese_fries.png",
  cheese_prez: "cheese_prez.png",
  cheese_sauce: "cheese_sauce.png",
  chicken_bites: "chicken_bites.png",
  chkn_american: "chkn_american.png",
  chkn_brgr: "chkn_brgr.png",
  chocolate_shake: "chocolate_shake.png",
  chocolate_sundae: "chocolate_sundae.png",
  classic_mojito: "classic_mojito.png",
  coca_cola: "coca_cola.png",
  coca_cola_zero: "coca_cola_zero.png",
  cortado: "cortado.png",
  curly_fries: "curly_fries.png",
  espresso: "espresso.png",
  fanta: "fanta.png",
  flat_white: "flat_white.png",
  grld_chkn_ranch: "grld_chkn_ranch.png",
  grld_chkn_sriracha_mayo: "grld_chkn_sriracha_mayo.png",
  honey_mustard: "honey_mustard.png",
  iced_americano: "iced_americano.png",
  iced_coconut_cream_matcha: "iced_coconut_cream_matcha.png",
  iced_double_matcha_latte: "iced_double_matcha_latte.png",
  iced_latte: "iced_latte.png",
  iced_matcha_latte: "iced_matcha_latte.png",
  iced_pistachio_latte: "iced_pistachio_latte.png",
  iced_pistachio_matcha: "iced_pistachio_matcha.png",
  iced_salted_caramel_latte: "iced_salted_caramel_latte.png",
  iced_salted_hazelnut_latte: "iced_salted_hazelnut_latte.png",
  iced_salted_vanilla_bean_latte: "iced_salted_vanilla_bean_latte.png",
  iced_salted_vanilla_bean_matcha: "iced_salted_vanilla_bean_matcha.png",
  iced_spanish_latte: "iced_spanish_latte.png",
  iced_spanish_matcha: "iced_spanish_matcha.png",
  iced_strawberry_matcha: "iced_strawberry_matcha.png",
  iced_white_matcha: "iced_white_matcha.png",
  iced_white_mocha_latte: "iced_white_mocha_latte.png",
  "j-bomb_double": "j-bomb_double.png",
  "j-bomb_single": "j-bomb_single.png",
  latte: "latte.png",
  lemon_mint_smoothie: "lemon_mint_smoothie.png",
  lotus_mini_pancakes: "lotus_mini_pancakes.png",
  lotus_shake: "lotus_shake.png",
  lotus_sundae: "lotus_sundae.png",
  macchiato: "macchiato.png",
  mango_coconut: "mango_coconut.png",
  martins_hotdog: "martins_hotdog.png",
  matcha_latte: "matcha_latte.png",
  mini_cookie_box_6_pieces: "mini_cookie_box_6_pieces.png",
  mix_mini_pancakes: "mix_mini_pancakes.png",
  nutella_mini_pancakes: "nutella_mini_pancakes.png",
  onion_rings: "onion_rings.png",
  oreo_shake: "oreo_shake.png",
  oreo_sundae: "oreo_sundae.png",
  original_double: "original_double.png",
  original_prez: "original_prez.png",
  original_single: "original_single.png",
  passionfruit_smoothie: "passionfruit_smoothie.png",
  passion_fruit_iced_tea: "passion_fruit_iced_tea.png",
  passion_fruit_lemonade_shaker: "passion_fruit_lemonade_shaker.png",
  passion_fruit_mojito: "passion_fruit_mojito.png",
  passion_fruit_redbull_mojito: "passion_fruit_redbull_mojito.png",
  peach_iced_tea: "peach_iced_tea.png",
  pina_colada_lemonade: "pina_colada_lemonade.png",
  pina_colada_lemonade_shaker: "pina_colada_lemonade_shaker.png",
  pink_lemonade_shaker: "pink_lemonade_shaker.png",
  pistachio_latte: "pistachio_latte.png",
  pistachio_matcha: "pistachio_matcha.png",
  pistachio_shake: "pistachio_shake.png",
  pistachio_sundaes: "pistachio_sundaes.png",
  ranch: "ranch.png",
  raspberry_iced_tea: "raspberry_iced_tea.png",
  red_bull: "red_bull.png",
  red_bull_sugar_free: "red_bull_sugar_free.png",
  red_bull_white_edition: "red_bull_white_edition.png",
  regular_fries: "regular_fries.png",
  salted_caramel_latte: "salted_caramel_latte.png",
  salted_hazelnut_latte: "salted_hazelnut_latte.png",
  salted_vanilla_bean_latte: "salted_vanilla_bean_latte.png",
  salted_vanilla_bean_matcha: "salted_vanilla_bean_matcha.png",
  spanish_latte: "spanish_latte.png",
  spanish_matcha: "spanish_matcha.png",
  sprite: "sprite.png",
  sriracha_mayo: "sriracha_mayo.png",
  strawberry_shake: "strawberry_shake.png",
  strawberry_smoothie: "strawberry_smoothie.png",
  strawberry_sundae: "strawberry_sundae.png",
  tangy_bbq: "tangy_bbq.png",
  the_cheese_brgr_double: "the_cheese_brgr_double.png",
  the_cheese_brgr_single: "the_cheese_brgr_single.png",
  the_truffle_double: "the_truffle_double.png",
  the_truffle_single: "the_truffle_single.png",
  truffle_fries: "truffle_fries.png",
  vanilla_cone: "vanilla_cone.png",
  vanilla_shake: "vanilla_shake.png",
  vanilla_sundae: "vanilla_sundae.png",
  water: "water.png",
  watermelon: "watermelon.png",
  white_matcha: "white_matcha.png",
  white_mocha_latte: "white_mocha_latte.png",
};

const ITEM_IMAGE_ALIASES: Record<string, string> = {
  cheese_brgr_double: "the_cheese_brgr_double",
  cheese_brgr_single: "the_cheese_brgr_single",
  chkn_bites: "chicken_bites",
  grld_chkn_sriracha: "grld_chkn_sriracha_mayo",
  ice_cream_chocolate: "chocolate_sundae",
  ice_cream_lotus: "lotus_sundae",
  ice_cream_oreo: "oreo_sundae",
  ice_cream_pistachio: "pistachio_sundaes",
  ice_cream_strawberry: "strawberry_sundae",
  ice_cream_vanilla: "vanilla_sundae",
  mini_pancakes_lotus: "lotus_mini_pancakes",
  mini_pancakes_mix: "mix_mini_pancakes",
  mini_pancakes_nutella: "nutella_mini_pancakes",
};

function toImageSlug(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "_");
}

export function getMenuItemImageSrc(itemName: string): string | null {
  const itemSlug = toImageSlug(itemName);
  const imageSlug = ITEM_IMAGE_ALIASES[itemSlug] ?? itemSlug;
  const fileName = IMAGE_FILES[imageSlug];

  return fileName ? `/menu-images/${fileName}` : null;
}
